(() => {
  "use strict";

  const root = typeof window !== "undefined" ? window : globalThis;
  const RiftRun = root.RiftRun || {};

  const DATA_URLS = {
    champions: "./data/champions.json",
    items: "./data/items.json",
    abilities: "./data/abilities.json",
    championStats: "./data/champion-stats.json",
  };

  const STORAGE_KEYS = {
    settings: "riftle.riftRun.v1.settings",
    records: "riftle.riftRun.v1.records",
    activeRun: "riftle.riftRun.v1.activeRun",
  };

  const RUN_CONFIG = {
    version: 1,
    firstChoiceStage: 3,
    choiceEvery: 1,
    cashOutEvery: 5,
    specialEvery: 4,
    optionCount: 3,
    maxRecentEntities: 18,
    maxRecentTypes: 5,
    maxRecentMetrics: 6,
    startingStability: 100,
    failStability: 0,
    stagePreviewMs: 0,
    feedbackDelayMs: 520,
    rapidFireRounds: 5,
    openingStages: [
      { type: "higherLower", category: "items", metricId: "item.gold" },
      { type: "identify", category: "champions" },
    ],
  };

  const SCORING_CONFIG = {
    baseReward: 420,
    specialRewardBonus: 260,
    difficultyRewardScale: 1.55,
    multiplierStart: 1,
    multiplierCap: 9.5,
    comboStep: 0.08,
    riskMultiplierScale: 0.38,
    correctStabilityGain: 3,
    wrongStabilityLoss: 18,
    oneShotLoss: 34,
    partialLoss: 8,
    cashOutBankShare: 0.72,
    continueBonus: 0.18,
    wrongScoreKeep: 0.62,
  };

  const DIFFICULTY_CONFIG = {
    min: 0.08,
    max: 0.96,
    earlyTarget: 0.2,
    stageSlope: 0.028,
    waveAmount: 0.11,
    breathingRoomEvery: 7,
    specialBump: 0.12,
    closeGapHardness: 0.13,
    exactToleranceEasy: 0.18,
    exactToleranceHard: 0.055,
  };

  const CATEGORY_CONFIG = {
    champions: {
      label: "Champions",
      shortLabel: "Champion",
      accent: "#68d9ff",
    },
    items: {
      label: "Items",
      shortLabel: "Item",
      accent: "#f0cf85",
    },
    abilities: {
      label: "Abilities",
      shortLabel: "Ability",
      accent: "#bba0ff",
    },
  };

  const CHALLENGE_TYPES = {
    higherLower: {
      label: "Higher / Lower",
      shortLabel: "Compare",
      baseWeight: 1.45,
      minStage: 1,
    },
    order: {
      label: "Order",
      shortLabel: "Order",
      baseWeight: 0.92,
      minStage: 3,
      specialWeight: 1.1,
    },
    exact: {
      label: "Exact / Estimate",
      shortLabel: "Estimate",
      baseWeight: 0.92,
      minStage: 2,
      specialWeight: 0.72,
    },
    outlier: {
      label: "Find the Outlier",
      shortLabel: "Outlier",
      baseWeight: 0.72,
      minStage: 4,
      categories: ["champions", "items"],
    },
    match: {
      label: "Match / Pair",
      shortLabel: "Match",
      baseWeight: 0.7,
      minStage: 5,
      categories: ["abilities"],
      specialWeight: 1,
    },
    identify: {
      label: "Identify",
      shortLabel: "Identify",
      baseWeight: 0.9,
      minStage: 2,
    },
    constraint: {
      label: "Constraint Search",
      shortLabel: "Search",
      baseWeight: 0.72,
      minStage: 5,
      categories: ["champions"],
      specialWeight: 1.05,
    },
    rapidFire: {
      label: "Rapid Fire",
      shortLabel: "Rapid",
      baseWeight: 0,
      minStage: 6,
      categories: ["champions", "items", "abilities"],
      specialOnly: true,
      specialWeight: 1.15,
    },
  };

  const MODIFIERS = {
    narrowGap: {
      label: "Narrow Gap",
      risk: 0.2,
      difficulty: 0.16,
      reward: 0.22,
      types: ["higherLower", "rapidFire"],
      description: "Values are deliberately close.",
    },
    noNames: {
      label: "No Names",
      risk: 0.18,
      difficulty: 0.12,
      reward: 0.16,
      types: ["identify", "order", "match"],
      description: "Names are hidden until the answer lands.",
    },
    noPortraits: {
      label: "No Portraits",
      risk: 0.12,
      difficulty: 0.08,
      reward: 0.12,
      types: ["higherLower", "order", "constraint"],
      description: "Images are stripped out.",
    },
    reverse: {
      label: "Reverse",
      risk: 0.14,
      difficulty: 0.1,
      reward: 0.14,
      types: ["order", "outlier"],
      description: "The natural direction is flipped.",
    },
    timePressure: {
      label: "Time Pressure",
      risk: 0.22,
      difficulty: 0.13,
      reward: 0.24,
      types: ["higherLower", "identify", "rapidFire", "outlier"],
      timeLimit: 11,
      description: "A short timer is active.",
    },
    oneShot: {
      label: "One Shot",
      risk: 0.28,
      difficulty: 0.08,
      reward: 0.3,
      types: ["exact", "constraint", "match", "order"],
      description: "A miss hits stability harder.",
    },
    mixedLevels: {
      label: "Mixed Levels",
      risk: 0.16,
      difficulty: 0.11,
      reward: 0.16,
      categories: ["champions"],
      types: ["higherLower", "order", "exact"],
      description: "Level 1 and level 18 stats can both appear.",
    },
    fog: {
      label: "Fog",
      risk: 0.16,
      difficulty: 0.1,
      reward: 0.15,
      types: ["higherLower", "constraint", "outlier"],
      description: "Some useful context stays hidden until reveal.",
    },
    doubleCondition: {
      label: "Double Condition",
      risk: 0.2,
      difficulty: 0.15,
      reward: 0.22,
      types: ["constraint", "outlier"],
      description: "More than one rule matters.",
    },
    precision: {
      label: "Precision",
      risk: 0.2,
      difficulty: 0.15,
      reward: 0.22,
      types: ["exact"],
      description: "Estimates need to be tighter.",
    },
    closeChoices: {
      label: "Close Choices",
      risk: 0.18,
      difficulty: 0.13,
      reward: 0.18,
      types: ["identify", "match", "outlier"],
      description: "The decoys are from a similar pool.",
    },
    obscureMetric: {
      label: "Obscure Metric",
      risk: 0.16,
      difficulty: 0.13,
      reward: 0.18,
      types: ["higherLower", "order", "exact"],
      description: "The stat is less commonly memorized.",
    },
  };

  const METRICS = [
    {
      id: "champion.healthLevel1",
      category: "champions",
      key: "healthLevel1",
      label: "Health at level 1",
      shortLabel: "HP",
      unit: "",
      group: "core",
      obscurity: 0.1,
      valid: "positive",
    },
    {
      id: "champion.healthLevel18",
      category: "champions",
      key: "healthLevel18",
      label: "Health at level 18",
      shortLabel: "HP 18",
      group: "mixedLevel",
      obscurity: 0.25,
      valid: "positive",
    },
    {
      id: "champion.attackDamageLevel1",
      category: "champions",
      key: "attackDamageLevel1",
      label: "Attack damage at level 1",
      shortLabel: "AD",
      group: "core",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "champion.attackDamageLevel18",
      category: "champions",
      key: "attackDamageLevel18",
      label: "Attack damage at level 18",
      shortLabel: "AD 18",
      group: "mixedLevel",
      obscurity: 0.28,
      valid: "positive",
    },
    {
      id: "champion.armorLevel1",
      category: "champions",
      key: "armorLevel1",
      label: "Armor at level 1",
      shortLabel: "Armor",
      group: "core",
      obscurity: 0.16,
      valid: "positive",
    },
    {
      id: "champion.magicResistLevel1",
      category: "champions",
      key: "magicResistLevel1",
      label: "Magic resist at level 1",
      shortLabel: "MR",
      group: "core",
      obscurity: 0.2,
      valid: "positive",
    },
    {
      id: "champion.attackRange",
      category: "champions",
      key: "attackRange",
      label: "Attack range",
      shortLabel: "Range",
      group: "identity",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "champion.moveSpeed",
      category: "champions",
      key: "moveSpeed",
      label: "Move speed",
      shortLabel: "MS",
      group: "identity",
      obscurity: 0.24,
      valid: "positive",
    },
    {
      id: "champion.releaseYear",
      category: "champions",
      key: "releaseYear",
      label: "Release year",
      shortLabel: "Year",
      group: "profile",
      obscurity: 0.3,
      valid: "positive",
    },
    {
      id: "item.gold",
      category: "items",
      key: "gold",
      label: "Total cost",
      shortLabel: "Cost",
      unit: "gold",
      group: "core",
      obscurity: 0.08,
      valid: "positive",
    },
    {
      id: "item.attackDamage",
      category: "items",
      key: "attackDamage",
      label: "Attack damage",
      shortLabel: "AD",
      group: "stats",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "item.abilityPower",
      category: "items",
      key: "abilityPower",
      label: "Ability power",
      shortLabel: "AP",
      group: "stats",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "item.health",
      category: "items",
      key: "health",
      label: "Health",
      shortLabel: "HP",
      group: "stats",
      obscurity: 0.14,
      valid: "positive",
    },
    {
      id: "item.armor",
      category: "items",
      key: "armor",
      label: "Armor",
      shortLabel: "Armor",
      group: "stats",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "item.magicResist",
      category: "items",
      key: "magicResist",
      label: "Magic resist",
      shortLabel: "MR",
      group: "stats",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "item.abilityHaste",
      category: "items",
      key: "abilityHaste",
      label: "Ability haste",
      shortLabel: "Haste",
      group: "stats",
      obscurity: 0.22,
      valid: "positive",
    },
    {
      id: "item.moveSpeed",
      category: "items",
      key: "moveSpeed",
      label: "Move speed",
      shortLabel: "MS",
      group: "stats",
      obscurity: 0.24,
      valid: "positive",
    },
    {
      id: "item.attackSpeed",
      category: "items",
      key: "attackSpeed",
      label: "Attack speed",
      shortLabel: "AS",
      unit: "%",
      group: "stats",
      obscurity: 0.2,
      valid: "positive",
    },
    {
      id: "ability.abilityCooldown",
      category: "abilities",
      key: "abilityCooldown",
      label: "Cooldown at rank 1",
      shortLabel: "Cooldown",
      unit: "s",
      group: "core",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "ability.abilityCost",
      category: "abilities",
      key: "abilityCost",
      label: "Resource cost at rank 1",
      shortLabel: "Cost",
      group: "core",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "ability.abilityRange",
      category: "abilities",
      key: "abilityRange",
      label: "Cast range",
      shortLabel: "Range",
      group: "stats",
      obscurity: 0.22,
      valid: "positive",
    },
    {
      id: "ability.abilityDamage",
      category: "abilities",
      key: "abilityDamage",
      label: "Listed base damage",
      shortLabel: "Damage",
      group: "stats",
      obscurity: 0.26,
      valid: "positive",
    },
    {
      id: "ability.abilitySlow",
      category: "abilities",
      key: "abilitySlow",
      label: "Slow strength",
      shortLabel: "Slow",
      unit: "%",
      group: "stats",
      obscurity: 0.34,
      valid: "positive",
    },
  ];

  const TRAIT_RULES = [
    { id: "resource", label: "Resource", category: "champions", minSame: 3 },
    { id: "rangeType", label: "Range type", category: "champions", minSame: 3 },
    { id: "position", label: "Position", category: "champions", minSame: 3 },
    { id: "region", label: "Region", category: "champions", minSame: 3 },
    { id: "tags", label: "Item tag", category: "items", minSame: 3 },
  ];

  RiftRun.config = {
    DATA_URLS,
    STORAGE_KEYS,
    RUN_CONFIG,
    SCORING_CONFIG,
    DIFFICULTY_CONFIG,
    CATEGORY_CONFIG,
    CHALLENGE_TYPES,
    MODIFIERS,
    METRICS,
    TRAIT_RULES,
  };

  root.RiftRun = RiftRun;

  if (typeof module !== "undefined" && module.exports) {
    module.exports = RiftRun.config;
  }
})();
