(() => {
  "use strict";

  const root = typeof window !== "undefined" ? window : globalThis;
  const RiftRun = root.RiftRun || {};

  const DATA_URLS = {
    champions: "./data/champions.json",
    items: "./data/items.json",
    itemTranslations: "./data/item-translations-ru.json",
    abilities: "./data/abilities.json",
    championStats: "./data/champion-stats.json",
  };

  const STORAGE_KEYS = {
    settings: "riftle.riftRun.v1.settings",
    records: "riftle.riftRun.v1.records",
    activeRun: "riftle.riftRun.v1.activeRun",
  };

  const RUN_CONFIG = {
    version: 1,
    firstChoiceStage: 3,
    choiceEvery: 1,
    cashOutEvery: 5,
    specialEvery: 4,
    optionCount: 3,
    maxRecentEntities: 18,
    maxRecentTypes: 5,
    maxRecentMetrics: 6,
    startingStability: 100,
    failStability: 0,
    stagePreviewMs: 0,
    feedbackDelayMs: 520,
    rapidFireRounds: 5,
    openingStages: [
      { type: "higherLower", category: "items", metricId: "item.gold" },
      { type: "identify", category: "champions" },
    ],
  };

  const SCORING_CONFIG = {
    baseReward: 420,
    specialRewardBonus: 260,
    difficultyRewardScale: 1.55,
    multiplierStart: 1,
    multiplierCap: 9.5,
    comboStep: 0.08,
    riskMultiplierScale: 0.38,
    correctStabilityGain: 3,
    wrongStabilityLoss: 18,
    oneShotLoss: 34,
    partialLoss: 8,
    cashOutBankShare: 0.72,
    continueBonus: 0.18,
    wrongScoreKeep: 0.62,
  };

  const DIFFICULTY_CONFIG = {
    min: 0.08,
    max: 0.96,
    earlyTarget: 0.2,
    stageSlope: 0.028,
    waveAmount: 0.11,
    breathingRoomEvery: 7,
    specialBump: 0.12,
    closeGapHardness: 0.13,
    exactToleranceEasy: 0.18,
    exactToleranceHard: 0.055,
  };

  const CATEGORY_CONFIG = {
    champions: {
      label: "Champions",
      shortLabel: "Champion",
      accent: "#68d9ff",
    },
    items: {
      label: "Items",
      shortLabel: "Item",
      accent: "#f0cf85",
    },
    abilities: {
      label: "Abilities",
      shortLabel: "Ability",
      accent: "#bba0ff",
    },
  };

  const CHALLENGE_TYPES = {
    higherLower: {
      label: "Higher / Lower",
      shortLabel: "Compare",
      baseWeight: 1.45,
      minStage: 1,
    },
    order: {
      label: "Order",
      shortLabel: "Order",
      baseWeight: 0.92,
      minStage: 3,
      specialWeight: 1.1,
    },
    exact: {
      label: "Exact / Estimate",
      shortLabel: "Estimate",
      baseWeight: 0.92,
      minStage: 2,
      specialWeight: 0.72,
    },
    outlier: {
      label: "Find the Outlier",
      shortLabel: "Outlier",
      baseWeight: 0.72,
      minStage: 4,
      categories: ["champions", "items"],
    },
    pickExtreme: {
      label: "Pick the Extreme",
      shortLabel: "Pick",
      baseWeight: 0.82,
      minStage: 4,
      specialWeight: 0.8,
    },
    match: {
      label: "Match / Pair",
      shortLabel: "Match",
      baseWeight: 0.7,
      minStage: 5,
      categories: ["abilities"],
      specialWeight: 1,
    },
    identify: {
      label: "Identify",
      shortLabel: "Identify",
      baseWeight: 0.9,
      minStage: 2,
    },
    constraint: {
      label: "Constraint Search",
      shortLabel: "Search",
      baseWeight: 0.72,
      minStage: 5,
      categories: ["champions"],
      specialWeight: 1.05,
    },
    rapidFire: {
      label: "Rapid Fire",
      shortLabel: "Rapid",
      baseWeight: 0,
      minStage: 6,
      categories: ["champions", "items", "abilities"],
      specialOnly: true,
      specialWeight: 1.15,
    },
  };

  const MODIFIERS = {
    narrowGap: {
      label: "Narrow Gap",
      risk: 0.2,
      difficulty: 0.16,
      reward: 0.22,
      types: ["higherLower", "rapidFire"],
      description: "Values are deliberately close.",
    },
    noNames: {
      label: "No Names",
      risk: 0.18,
      difficulty: 0.12,
      reward: 0.16,
      types: ["identify", "order", "match"],
      description: "Names are hidden until the answer lands.",
    },
    noPortraits: {
      label: "No Portraits",
      risk: 0.12,
      difficulty: 0.08,
      reward: 0.12,
      types: ["higherLower", "order", "constraint"],
      description: "Images are stripped out.",
    },
    reverse: {
      label: "Reverse",
      risk: 0.14,
      difficulty: 0.1,
      reward: 0.14,
      types: ["order", "outlier"],
      description: "The natural direction is flipped.",
    },
    timePressure: {
      label: "Time Pressure",
      risk: 0.22,
      difficulty: 0.13,
      reward: 0.24,
      types: ["higherLower", "identify", "rapidFire", "outlier"],
      timeLimit: 11,
      description: "A short timer is active.",
    },
    oneShot: {
      label: "One Shot",
      risk: 0.28,
      difficulty: 0.08,
      reward: 0.3,
      types: ["exact", "constraint", "match", "order"],
      description: "A miss hits stability harder.",
    },
    mixedLevels: {
      label: "Mixed Levels",
      risk: 0.16,
      difficulty: 0.11,
      reward: 0.16,
      categories: ["champions"],
      types: ["higherLower", "order", "exact"],
      description: "Level 1 and level 18 stats can both appear.",
    },
    fog: {
      label: "Fog",
      risk: 0.16,
      difficulty: 0.1,
      reward: 0.15,
      types: ["higherLower", "constraint", "outlier"],
      description: "Some useful context stays hidden until reveal.",
    },
    doubleCondition: {
      label: "Double Condition",
      risk: 0.2,
      difficulty: 0.15,
      reward: 0.22,
      types: ["constraint", "outlier"],
      description: "More than one rule matters.",
    },
    precision: {
      label: "Precision",
      risk: 0.2,
      difficulty: 0.15,
      reward: 0.22,
      types: ["exact"],
      description: "Estimates need to be tighter.",
    },
    closeChoices: {
      label: "Close Choices",
      risk: 0.18,
      difficulty: 0.13,
      reward: 0.18,
      types: ["identify", "match", "outlier"],
      description: "The decoys are from a similar pool.",
    },
    obscureMetric: {
      label: "Obscure Metric",
      risk: 0.16,
      difficulty: 0.13,
      reward: 0.18,
      types: ["higherLower", "order", "exact"],
      description: "The stat is less commonly memorized.",
    },
  };

  const METRICS = [
    {
      id: "champion.healthLevel1",
      category: "champions",
      key: "healthLevel1",
      label: "Health at level 1",
      shortLabel: "HP",
      unit: "",
      group: "core",
      obscurity: 0.1,
      valid: "positive",
    },
    {
      id: "champion.healthLevel18",
      category: "champions",
      key: "healthLevel18",
      label: "Health at level 18",
      shortLabel: "HP 18",
      group: "mixedLevel",
      obscurity: 0.25,
      valid: "positive",
    },
    {
      id: "champion.attackDamageLevel1",
      category: "champions",
      key: "attackDamageLevel1",
      label: "Attack damage at level 1",
      shortLabel: "AD",
      group: "core",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "champion.attackDamageLevel18",
      category: "champions",
      key: "attackDamageLevel18",
      label: "Attack damage at level 18",
      shortLabel: "AD 18",
      group: "mixedLevel",
      obscurity: 0.28,
      valid: "positive",
    },
    {
      id: "champion.armorLevel1",
      category: "champions",
      key: "armorLevel1",
      label: "Armor at level 1",
      shortLabel: "Armor",
      group: "core",
      obscurity: 0.16,
      valid: "positive",
    },
    {
      id: "champion.armorLevel18",
      category: "champions",
      key: "armorLevel18",
      label: "Armor at level 18",
      shortLabel: "Armor 18",
      group: "mixedLevel",
      obscurity: 0.3,
      valid: "positive",
    },
    {
      id: "champion.magicResistLevel1",
      category: "champions",
      key: "magicResistLevel1",
      label: "Magic resist at level 1",
      shortLabel: "MR",
      group: "core",
      obscurity: 0.2,
      valid: "positive",
    },
    {
      id: "champion.magicResistLevel18",
      category: "champions",
      key: "magicResistLevel18",
      label: "Magic resist at level 18",
      shortLabel: "MR 18",
      group: "mixedLevel",
      obscurity: 0.32,
      valid: "positive",
    },
    {
      id: "champion.attackSpeedLevel1",
      category: "champions",
      key: "attackSpeedLevel1",
      label: "Attack speed at level 1",
      shortLabel: "AS",
      group: "core",
      obscurity: 0.26,
      valid: "positive",
    },
    {
      id: "champion.healthRegenLevel1",
      category: "champions",
      key: "healthRegenLevel1",
      label: "Health regen at level 1",
      shortLabel: "HP regen",
      group: "stats",
      obscurity: 0.34,
      valid: "positive",
    },
    {
      id: "champion.manaRegenLevel1",
      category: "champions",
      key: "manaRegenLevel1",
      label: "Mana regen at level 1",
      shortLabel: "Mana regen",
      group: "stats",
      obscurity: 0.38,
      valid: "positive",
    },
    {
      id: "champion.attackRange",
      category: "champions",
      key: "attackRange",
      label: "Attack range",
      shortLabel: "Range",
      group: "identity",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "champion.moveSpeed",
      category: "champions",
      key: "moveSpeed",
      label: "Move speed",
      shortLabel: "MS",
      group: "identity",
      obscurity: 0.24,
      valid: "positive",
    },
    {
      id: "champion.releaseYear",
      category: "champions",
      key: "releaseYear",
      label: "Release year",
      shortLabel: "Year",
      group: "profile",
      obscurity: 0.3,
      valid: "positive",
    },
    {
      id: "item.gold",
      category: "items",
      key: "gold",
      label: "Total cost",
      shortLabel: "Cost",
      unit: "gold",
      group: "core",
      obscurity: 0.08,
      valid: "positive",
    },
    {
      id: "item.attackDamage",
      category: "items",
      key: "attackDamage",
      label: "Attack damage",
      shortLabel: "AD",
      group: "stats",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "item.abilityPower",
      category: "items",
      key: "abilityPower",
      label: "Ability power",
      shortLabel: "AP",
      group: "stats",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "item.health",
      category: "items",
      key: "health",
      label: "Health",
      shortLabel: "HP",
      group: "stats",
      obscurity: 0.14,
      valid: "positive",
    },
    {
      id: "item.armor",
      category: "items",
      key: "armor",
      label: "Armor",
      shortLabel: "Armor",
      group: "stats",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "item.magicResist",
      category: "items",
      key: "magicResist",
      label: "Magic resist",
      shortLabel: "MR",
      group: "stats",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "item.abilityHaste",
      category: "items",
      key: "abilityHaste",
      label: "Ability haste",
      shortLabel: "Haste",
      group: "stats",
      obscurity: 0.22,
      valid: "positive",
    },
    {
      id: "item.moveSpeed",
      category: "items",
      key: "moveSpeed",
      label: "Move speed",
      shortLabel: "MS",
      group: "stats",
      obscurity: 0.24,
      valid: "positive",
    },
    {
      id: "item.attackSpeed",
      category: "items",
      key: "attackSpeed",
      label: "Attack speed",
      shortLabel: "AS",
      unit: "%",
      group: "stats",
      obscurity: 0.2,
      valid: "positive",
    },
    {
      id: "item.critChance",
      category: "items",
      key: "critChance",
      label: "Critical strike chance",
      shortLabel: "Crit",
      unit: "%",
      group: "stats",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "item.lifeSteal",
      category: "items",
      key: "lifeSteal",
      label: "Life steal",
      shortLabel: "Life steal",
      unit: "%",
      group: "stats",
      obscurity: 0.24,
      valid: "positive",
    },
    {
      id: "item.lethality",
      category: "items",
      key: "lethality",
      label: "Lethality",
      shortLabel: "Lethality",
      group: "stats",
      obscurity: 0.26,
      valid: "positive",
    },
    {
      id: "item.percentArmorPenetration",
      category: "items",
      key: "percentArmorPenetration",
      label: "Armor penetration",
      shortLabel: "Armor pen",
      unit: "%",
      group: "stats",
      obscurity: 0.3,
      valid: "positive",
    },
    {
      id: "item.healShieldPower",
      category: "items",
      key: "healShieldPower",
      label: "Heal and shield power",
      shortLabel: "H/S power",
      unit: "%",
      group: "stats",
      obscurity: 0.34,
      valid: "positive",
    },
    {
      id: "ability.abilityCooldown",
      category: "abilities",
      key: "abilityCooldown",
      label: "Cooldown at rank 1",
      shortLabel: "Cooldown",
      unit: "s",
      group: "core",
      obscurity: 0.12,
      valid: "positive",
    },
    {
      id: "ability.abilityCost",
      category: "abilities",
      key: "abilityCost",
      label: "Resource cost at rank 1",
      shortLabel: "Cost",
      group: "core",
      obscurity: 0.18,
      valid: "positive",
    },
    {
      id: "ability.abilityRange",
      category: "abilities",
      key: "abilityRange",
      label: "Cast range",
      shortLabel: "Range",
      group: "stats",
      obscurity: 0.22,
      valid: "positive",
    },
    {
      id: "ability.abilityDamage",
      category: "abilities",
      key: "abilityDamage",
      label: "Listed base damage",
      shortLabel: "Damage",
      group: "stats",
      obscurity: 0.26,
      valid: "positive",
    },
    {
      id: "ability.abilitySlow",
      category: "abilities",
      key: "abilitySlow",
      label: "Slow strength",
      shortLabel: "Slow",
      unit: "%",
      group: "stats",
      obscurity: 0.34,
      valid: "positive",
    },
    {
      id: "ability.abilityHealing",
      category: "abilities",
      key: "abilityHealing",
      label: "Listed healing",
      shortLabel: "Healing",
      group: "stats",
      obscurity: 0.36,
      valid: "positive",
    },
    {
      id: "ability.abilityShield",
      category: "abilities",
      key: "abilityShield",
      label: "Listed shield",
      shortLabel: "Shield",
      group: "stats",
      obscurity: 0.36,
      valid: "positive",
    },
    {
      id: "ability.abilityMoveSpeed",
      category: "abilities",
      key: "abilityMoveSpeed",
      label: "Move speed bonus",
      shortLabel: "MS bonus",
      unit: "%",
      group: "stats",
      obscurity: 0.38,
      valid: "positive",
    },
  ];

  const TRAIT_RULES = [
    { id: "resource", label: "Resource", category: "champions", minSame: 3 },
    { id: "rangeType", label: "Range type", category: "champions", minSame: 3 },
    { id: "position", label: "Position", category: "champions", minSame: 3 },
    { id: "region", label: "Region", category: "champions", minSame: 3 },
    { id: "tags", label: "Item tag", category: "items", minSame: 3 },
  ];

  const I18N = {
    categoryLabels: {
      champions: { en: "Champions", ru: "Чемпионы" },
      items: { en: "Items", ru: "Предметы" },
      abilities: { en: "Abilities", ru: "Умения" },
    },
    categoryShortLabels: {
      champions: { en: "Champion", ru: "Чемпион" },
      items: { en: "Item", ru: "Предмет" },
      abilities: { en: "Ability", ru: "Умение" },
    },
    typeLabels: {
      higherLower: { en: "Higher / Lower", ru: "Больше / меньше" },
      order: { en: "Order", ru: "Порядок" },
      exact: { en: "Exact / Estimate", ru: "Оценка числа" },
      outlier: { en: "Find the Outlier", ru: "Найди лишнее" },
      pickExtreme: { en: "Pick the Extreme", ru: "Выбери крайнее" },
      match: { en: "Match / Pair", ru: "Сопоставление" },
      identify: { en: "Identify", ru: "Узнай объект" },
      constraint: { en: "Constraint Search", ru: "Поиск по условиям" },
      rapidFire: { en: "Rapid Fire", ru: "Блиц" },
    },
    metricLabels: {
      "champion.healthLevel1": { en: "Health at level 1", ru: "Здоровье на 1 уровне" },
      "champion.healthLevel18": { en: "Health at level 18", ru: "Здоровье на 18 уровне" },
      "champion.attackDamageLevel1": { en: "Attack damage at level 1", ru: "Сила атаки на 1 уровне" },
      "champion.attackDamageLevel18": { en: "Attack damage at level 18", ru: "Сила атаки на 18 уровне" },
      "champion.armorLevel1": { en: "Armor at level 1", ru: "Броня на 1 уровне" },
      "champion.armorLevel18": { en: "Armor at level 18", ru: "Броня на 18 уровне" },
      "champion.magicResistLevel1": { en: "Magic resist at level 1", ru: "Сопротивление магии на 1 уровне" },
      "champion.magicResistLevel18": { en: "Magic resist at level 18", ru: "Сопротивление магии на 18 уровне" },
      "champion.attackSpeedLevel1": { en: "Attack speed at level 1", ru: "Скорость атаки на 1 уровне" },
      "champion.healthRegenLevel1": { en: "Health regen at level 1", ru: "Регенерация здоровья на 1 уровне" },
      "champion.manaRegenLevel1": { en: "Mana regen at level 1", ru: "Регенерация маны на 1 уровне" },
      "champion.attackRange": { en: "Attack range", ru: "Дальность атаки" },
      "champion.moveSpeed": { en: "Move speed", ru: "Скорость передвижения" },
      "champion.releaseYear": { en: "Release year", ru: "Год выхода" },
      "item.gold": { en: "Total cost", ru: "Полная стоимость" },
      "item.attackDamage": { en: "Attack damage", ru: "Сила атаки" },
      "item.abilityPower": { en: "Ability power", ru: "Сила умений" },
      "item.health": { en: "Health", ru: "Здоровье" },
      "item.armor": { en: "Armor", ru: "Броня" },
      "item.magicResist": { en: "Magic resist", ru: "Сопротивление магии" },
      "item.abilityHaste": { en: "Ability haste", ru: "Ускорение умений" },
      "item.moveSpeed": { en: "Move speed", ru: "Скорость передвижения" },
      "item.attackSpeed": { en: "Attack speed", ru: "Скорость атаки" },
      "item.critChance": { en: "Critical strike chance", ru: "Шанс критического удара" },
      "item.lifeSteal": { en: "Life steal", ru: "Вампиризм" },
      "item.lethality": { en: "Lethality", ru: "Летальность" },
      "item.percentArmorPenetration": { en: "Armor penetration", ru: "Пробивание брони" },
      "item.healShieldPower": { en: "Heal and shield power", ru: "Сила лечения и щитов" },
      "ability.abilityCooldown": { en: "Cooldown at rank 1", ru: "Перезарядка на 1 ранге" },
      "ability.abilityCost": { en: "Resource cost at rank 1", ru: "Стоимость ресурса на 1 ранге" },
      "ability.abilityRange": { en: "Cast range", ru: "Дальность применения" },
      "ability.abilityDamage": { en: "Listed base damage", ru: "Указанный базовый урон" },
      "ability.abilitySlow": { en: "Slow strength", ru: "Сила замедления" },
      "ability.abilityHealing": { en: "Listed healing", ru: "Указанное лечение" },
      "ability.abilityShield": { en: "Listed shield", ru: "Указанный щит" },
      "ability.abilityMoveSpeed": { en: "Move speed bonus", ru: "Бонус скорости передвижения" },
    },
    metricShortLabels: {
      "champion.healthLevel1": { en: "HP", ru: "Здоровье" },
      "champion.healthLevel18": { en: "HP 18", ru: "Здоровье 18" },
      "champion.attackDamageLevel1": { en: "AD", ru: "СА" },
      "champion.attackDamageLevel18": { en: "AD 18", ru: "СА 18" },
      "champion.armorLevel1": { en: "Armor", ru: "Броня" },
      "champion.armorLevel18": { en: "Armor 18", ru: "Броня 18" },
      "champion.magicResistLevel1": { en: "MR", ru: "Сопр. магии" },
      "champion.magicResistLevel18": { en: "MR 18", ru: "Сопр. магии 18" },
      "champion.attackSpeedLevel1": { en: "AS", ru: "Скор. атаки" },
      "champion.healthRegenLevel1": { en: "HP regen", ru: "Рег. здоровья" },
      "champion.manaRegenLevel1": { en: "Mana regen", ru: "Рег. маны" },
      "champion.attackRange": { en: "Range", ru: "Дальность" },
      "champion.moveSpeed": { en: "MS", ru: "Скорость" },
      "champion.releaseYear": { en: "Year", ru: "Год" },
      "item.gold": { en: "Cost", ru: "Стоимость" },
      "item.attackDamage": { en: "AD", ru: "СА" },
      "item.abilityPower": { en: "AP", ru: "СУ" },
      "item.health": { en: "HP", ru: "Здоровье" },
      "item.armor": { en: "Armor", ru: "Броня" },
      "item.magicResist": { en: "MR", ru: "Сопр. магии" },
      "item.abilityHaste": { en: "Haste", ru: "Ускорение" },
      "item.moveSpeed": { en: "MS", ru: "Скорость" },
      "item.attackSpeed": { en: "AS", ru: "Скор. атаки" },
      "item.critChance": { en: "Crit", ru: "Крит" },
      "item.lifeSteal": { en: "Life steal", ru: "Вампиризм" },
      "item.lethality": { en: "Lethality", ru: "Летальность" },
      "item.percentArmorPenetration": { en: "Armor pen", ru: "Проб. брони" },
      "item.healShieldPower": { en: "H/S power", ru: "Лечение/щиты" },
      "ability.abilityCooldown": { en: "Cooldown", ru: "Перезарядка" },
      "ability.abilityCost": { en: "Cost", ru: "Стоимость" },
      "ability.abilityRange": { en: "Range", ru: "Дальность" },
      "ability.abilityDamage": { en: "Damage", ru: "Урон" },
      "ability.abilitySlow": { en: "Slow", ru: "Замедление" },
      "ability.abilityHealing": { en: "Healing", ru: "Лечение" },
      "ability.abilityShield": { en: "Shield", ru: "Щит" },
      "ability.abilityMoveSpeed": { en: "MS bonus", ru: "Бонус скорости" },
    },
    traitLabels: {
      resource: { en: "Resource", ru: "Ресурс" },
      rangeType: { en: "Range type", ru: "Тип атаки" },
      position: { en: "Position", ru: "Позиция" },
      region: { en: "Region", ru: "Регион" },
      tags: { en: "Item tag", ru: "Тег предмета" },
    },
    traitValues: {
      Mana: { en: "Mana", ru: "мана" },
      Manaless: { en: "Manaless", ru: "без ресурса" },
      Energy: { en: "Energy", ru: "энергия" },
      Rage: { en: "Rage", ru: "ярость" },
      Fury: { en: "Fury", ru: "ярость" },
      Ferocity: { en: "Ferocity", ru: "свирепость" },
      Flow: { en: "Flow", ru: "поток" },
      Heat: { en: "Heat", ru: "перегрев" },
      Shield: { en: "Shield", ru: "щит" },
      Courage: { en: "Courage", ru: "храбрость" },
      Bloodthirst: { en: "Bloodthirst", ru: "жажда крови" },
      CrimsonRush: { en: "Crimson Rush", ru: "багровый прилив" },
      Melee: { en: "Melee", ru: "ближний бой" },
      Ranged: { en: "Ranged", ru: "дальний бой" },
      Top: { en: "Top", ru: "верхняя линия" },
      Jungle: { en: "Jungle", ru: "лес" },
      Middle: { en: "Middle", ru: "средняя линия" },
      Bottom: { en: "Bottom", ru: "нижняя линия" },
      Support: { en: "Support", ru: "поддержка" },
      Health: { en: "Health", ru: "здоровье" },
      SpellBlock: { en: "Magic resist", ru: "сопротивление магии" },
      MagicResist: { en: "Magic resist", ru: "сопротивление магии" },
      Armor: { en: "Armor", ru: "броня" },
      Damage: { en: "Damage", ru: "урон" },
      CriticalStrike: { en: "Critical strike", ru: "критический удар" },
      AttackSpeed: { en: "Attack speed", ru: "скорость атаки" },
      Boots: { en: "Boots", ru: "ботинки" },
      NonbootsMovement: { en: "Move speed", ru: "скорость передвижения" },
      ManaRegen: { en: "Mana regen", ru: "регенерация маны" },
      CooldownReduction: { en: "Ability haste", ru: "ускорение умений" },
      AbilityHaste: { en: "Ability haste", ru: "ускорение умений" },
      SpellDamage: { en: "Ability power", ru: "сила умений" },
      LifeSteal: { en: "Life steal", ru: "вампиризм" },
      ArmorPenetration: { en: "Armor penetration", ru: "пробивание брони" },
      MagicPenetration: { en: "Magic penetration", ru: "магическое пробивание" },
      OnHit: { en: "On-hit", ru: "при попадании" },
      Tenacity: { en: "Tenacity", ru: "стойкость" },
      Active: { en: "Active", ru: "активный эффект" },
      Consumable: { en: "Consumable", ru: "расходуемое" },
      GoldPer: { en: "Gold generation", ru: "получение золота" },
      Vision: { en: "Vision", ru: "обзор" },
      Lane: { en: "Lane", ru: "линия" },
      Jungle: { en: "Jungle", ru: "лес" },
    },
    modifierLabels: {
      narrowGap: { en: "Narrow Gap", ru: "Узкий разрыв" },
      noNames: { en: "No Names", ru: "Без названий" },
      noPortraits: { en: "No Portraits", ru: "Без изображений" },
      reverse: { en: "Reverse", ru: "Обратный порядок" },
      timePressure: { en: "Time Pressure", ru: "Ограничение времени" },
      oneShot: { en: "One Shot", ru: "Одна попытка" },
      mixedLevels: { en: "Mixed Levels", ru: "Разные уровни" },
      fog: { en: "Fog", ru: "Туман" },
      doubleCondition: { en: "Double Condition", ru: "Двойное условие" },
      precision: { en: "Precision", ru: "Точность" },
      closeChoices: { en: "Close Choices", ru: "Похожие варианты" },
      obscureMetric: { en: "Obscure Metric", ru: "Редкий параметр" },
    },
    modifierDescriptions: {
      narrowGap: { en: "Values are deliberately close.", ru: "Значения специально подобраны близко друг к другу." },
      noNames: { en: "Names are hidden until the answer lands.", ru: "Названия скрыты до ответа." },
      noPortraits: { en: "Images are stripped out.", ru: "Изображения скрыты." },
      reverse: { en: "The natural direction is flipped.", ru: "Обычный порядок развёрнут." },
      timePressure: { en: "A short timer is active.", ru: "Включён короткий таймер." },
      oneShot: { en: "A miss hits stability harder.", ru: "Ошибка сильнее бьёт по стабильности." },
      mixedLevels: { en: "Level 1 and level 18 stats can both appear.", ru: "Могут встречаться параметры 1 и 18 уровня." },
      fog: { en: "Some useful context stays hidden until reveal.", ru: "Часть контекста скрыта до раскрытия ответа." },
      doubleCondition: { en: "More than one rule matters.", ru: "Нужно учитывать больше одного правила." },
      precision: { en: "Estimates need to be tighter.", ru: "Оценка должна быть точнее." },
      closeChoices: { en: "The decoys are from a similar pool.", ru: "Ложные варианты подобраны из похожей группы." },
      obscureMetric: { en: "The stat is less commonly memorized.", ru: "Используется менее очевидный параметр." },
    },
    words: {
      item: { en: "item", ru: "предмет" },
      champion: { en: "champion", ru: "чемпиона" },
      ability: { en: "ability", ru: "умение" },
      higher: { en: "higher", ru: "больше" },
      lower: { en: "lower", ru: "меньше" },
      highest: { en: "highest", ru: "самое большое значение" },
      lowest: { en: "lowest", ru: "самое маленькое значение" },
      lowestToHighest: { en: "lowest to highest", ru: "от меньшего к большему" },
      highestToLowest: { en: "highest to lowest", ru: "от большего к меньшему" },
      none: { en: "None", ru: "Нет" },
      finished: { en: "Finished", ru: "Завершено" },
      cashedOut: { en: "Cashed out", ru: "Score забран" },
      stabilityCollapsed: { en: "Stability collapsed", ru: "Стабильность обнулилась" },
    },
  };

  RiftRun.config = {
    DATA_URLS,
    STORAGE_KEYS,
    RUN_CONFIG,
    SCORING_CONFIG,
    DIFFICULTY_CONFIG,
    CATEGORY_CONFIG,
    CHALLENGE_TYPES,
    MODIFIERS,
    METRICS,
    TRAIT_RULES,
    I18N,
  };

  root.RiftRun = RiftRun;

  if (typeof module !== "undefined" && module.exports) {
    module.exports = RiftRun.config;
  }
})();
